export enum EpicServices {
    ACCOUNT_SERVICE = 'https://account-public-service-prod03.ol.epicgames.com',
    AVATAR_SERVICE = 'https://avatar-service-prod.identity.live.on.epicgames.com',
    CALDERA_SERVICE = 'https://caldera-service-prod.ecosec.on.epicgames.com',
    STATS_SERVICE = 'https://statsproxy-public-service-live.ol.epicgames.com',
    LIGHTSWITCH_SERVICE = 'https://lightswitch-public-service-prod06.ol.epicgames.com',
    FORTNITE_SERVICE = 'https://fortnite-public-service-prod11.ol.epicgames.com',
    PARTY_SERVICE = 'https://party-service-prod.ol.epicgames.com',
    USER_SEARCH_SERVICE = 'https://user-search-service-prod.ol.epicgames.com',
    FRIEND_SERVICE = 'https://friends-public-service-prod.ol.epicgames.com'
}

export enum FortniteProfile {
    'campaign',
    'athena',
    'common_core',
    'common_public',
    'theater0',
    'theater1',
    'theater2',
    'outpost0'
}

export enum MCPOperation {
    'QueryPublicProfile',
    'QueryProfile',
    'ClaimLoginReward',
    'ClientQuestLogin',
    'PopulatePrerolledOffers',
    'PurchaseCatalogEntry',
    'FortRerollDailyQuest',
    'SetMtxPlatform',
    'RecycleItemBatch',
    'RecycleItem',
    'RefreshExpeditions',
    'PurchaseHomebaseNode',
    'OpenCardPackBatch',
    'OpenCardPack',
    'UnslotAllWorkers',
    'UnassignAllSquads',
    'TransmogItem',
    'SkipTutorial',
    'ModifyMission',
    'IssueFriendCode',
    'IncrementNamedCounterStat',
    'GetMcpTimeForLogin',
    'EquipCharCosmetic',
    'EndPrimaryMission',
    'EarnScore',
    'ConvertItem',
    'ConsumeItems',
    'CollectExpedition',
    'ClaimMissionAlertRewards',
    'ClaimCollectionBookRewards',
    'ClaimCollectedResources',
    'AssignWorkerToSquadBatch',
    'AssignWorkerToSquad',
    'ApplyAlteration',
    'ActivateConsumable',
    'SetAffiliateName',
    'ClaimMfaEnabled',
    'SetLoadoutName',
    'SetActiveHeroLoadout',
    'SetHomebaseName',
    'PurchaseOrUpgradeHomebaseNode',
    'AbandonExpedition',
    'UpdateOutpostCore',
    'UpdateDeployableBaseTierProgression',
    'CreateOrUpgradeOutpostItem',
    'CreateDeployableBaseItem',
    'UpgradeSlottedItem',
    'ConvertSlottedItem',
    'ClaimCollectionBookPageRewards',
    'SetBattleRoyaleBanner',
    'EndBattleRoyaleGame',
    'EquipBattleRoyaleCustomization',
    'UpdateBuildingLevelAndRating',
    'UnloadWarehouse',
    'DestroyWorldItems',
    'StorageTransfer',
    'PurchaseResearchStatUpgrade',
    'ClaimDifficultyIncreaseRewards'
}